<?php

namespace AppBundle\Entity\Repository;


/**
 * LinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkRepository extends AbstractRepository
{

}
